const requestsTypes = {
  ADD_NEW_REQUEST_START: "ADD_NEW_REQUEST_START",
  FETCH_REQUESTS_START: "FETCH_REQUESTS_START",
  FETCH_USER_REQUESTS: "FETCH_USER_REQUESTS",
  SET_REQUESTS: "SET_REQUESTS",
  DELETE_REQUEST_START: "DELETE_REQUEST_START",
  FETCH_REQUEST_START: "FETCH_REQUEST_START",
  SET_REQUEST: "SET_REQUEST",
  SET_USER_REQUESTS: "SET_USER_REQUESTS",
};

export default requestsTypes;
